version: '3.8'
services:
  movies:
    image: mohammedmeeraj/paymovies:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  flight:
    image: mohammedmeeraj/payflight:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
  recharge:
    image: mohammedmeeraj/payrecharge:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
