version: '3.8'
services:
  movies:
    image: mohammedmeeraj/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  flight:
    image: mohammedmeeraj/payflight:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: mohammedmeeraj/payrecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
