version: '3.8'
services:
  movies:
    image: mohammedmeeraj/movies:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  flight:
    image: mohammedmeeraj/flight:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
  recharge:
    image: mohammedmeeraj/recharge:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
