version: '3.8'
services:
  movies:
    image: mohammedmeeraj/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: mohammedmeeraj/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: mohammedmeeraj/payrecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
